POI_GROUPS = {
    "group1": {
        "amusement_park",
        "airport",
        "bus_station",
        "train_station",
        "transit_station",
        "store",
        "post_office",
        "tourist_attraction",
        "school",
        "university",
        "city_hall",
        "local_government_office",
        "courthouse",
        "embassy",
        "museum",
        "stadium",
        "gym",
        "parking",
        "hospital",
    },
    "group2": {
        "car_dealer",
        "hospital",
        "restaurant",
        "cafe",
        "amusement_park",
        "tourist_attraction",
        "clothing_store",
        "movie_theater",
        "shopping_mall",
        "supermarket",
        "shopping_mall",
        "pharmacy",
        "book_store",
        "store",
        "home_goods_store",
        "convenience_store",
        "gas_station",
        "lodging",
        "convenience_store",
    },
    "group3": {
        "school",
        "library",
        "art_gallery",
        "police",
        "place_of_worship",
    },
    "group4": {"bank", "atm"},
}


ALL_TYPES = set().union(*POI_GROUPS.values())
