TYPE_ATTRACTIVES = [
    {
        "amusement_park",
        "airport",
        "bus_station",
        "train_station",
        "transit_station",
        "store",
        "post_office",
        "tourist_attraction",
        "school",
        "university",
        "city_hall",
        "local_government_office",
        "courthouse",
        "embassy",
        "museum",
        "stadium",
        "gym",
        "parking",
        "hospital",
    },
    {
        "car_dealer",
        "hospital",
        "restaurant",
        "cafe",
        "amusement_park",
        "tourist_attraction",
        "clothing_store",
        "movie_theater",
        "shopping_mall",
        "supermarket",
        "shopping_mall",
        "pharmacy",
        "book_store",
        "store",
        "home_goods_store",
        "convenience_store",
        "gas_station",
        "lodging",
        "convenience_store",
    },
    {
        "school",
        "library",
        "art_gallery",
        "police",
        "place_of_worship",
    },
    {"bank", "atm"},
]

# GROUPS = {
#     "group 1": [
#         "kickboxing school",
#         "resort hotel",
#         "business park",
#         "free parking lot",
#         "bilingual school",
#         "post office",
#         "stadium",
#         "art school",
#         "heliport",
#         "business center",
#         "police academy",
#         "public university",
#         "event venue",
#         "visa and passport office",
#         "embassy",
#         "transport hub",
#         "soccer field",
#         "subway station",
#         "taxi stand",
#         "public educational institution",
#         "athletic park",
#         "agricultural high school",
#         "drivers license training school",
#         "public parking space",
#         "train station",
#         "education center",
#         "bus stop",
#         "regional airport",
#         "higher secondary school",
#         "museum",
#         "local government office",
#         "bus station",
#         "special education school",
#         "international airport",
#         "ferry terminal",
#         "city courthouse",
#         "public safety office",
#         "elementary school",
#         "government office",
#         "institute of technology",
#         "government",
#         "customs office",
#         "technical school",
#         "history museum",
#         "private university",
#         "parking lot for bicycles",
#         "art gallery",
#         "transit station",
#         "athletic park",
#         "drivers license office",
#         "language school",
#         "community school",
#         "high school",
#         "government hospital",
#         "government college",
#         "secondary school",
#         "parking garage",
#         "police department",
#         "farm school",
#         "vocational school",
#         "airline",
#         "public library",
#         "courthouse",
#         "school administration office",
#         "traffic police station",
#         "senior high school",
#         "parking garage",
#         "police department",
#         "farm school",
#         "airport",
#         "technical university",
#         "heritage preservation",
#         "police",
#         "gym",
#         "study at home school",
#         "love hotel",
#         "academic department",
#     ],
#     "group 2": [
#         "kickboxing school",
#         "motorcycle shop",
#         "resort hotel",
#         "event ticket seller",
#         "alcohol retail monopoly",
#         "lodge",
#         "medical supply store",
#         "kyoto style japanese restaurant",
#         "tobacco shop",
#         "cooking class",
#         "stadium",
#         "cottage rental",
#         "bedroom furniture store",
#         "singaporean restaurant",
#         "model shop",
#         "jujitsu school",
#         "copying supply store",
#         "deli",
#         "european grocery store",
#         "motorcycle parts store",
#         "french steakhouse restaurant",
#         "karaoke bar",
#         "novelty store",
#         "asian fusion restaurant",
#         "countertop store",
#         "soccer store",
#         "computer store",
#         "comic cafe",
#         "laotian restaurant",
#         "observation deck",
#         "south asian restaurant",
#         "chicken restaurant",
#         "gift shop",
#         "event venue",
#         "dried flower shop",
#         "food producer",
#         "beauty supply store",
#         "computer service",
#         "computer desk store",
#         "computer support and services",
#         "fondue restaurant",
#         "watch store",
#         "tire shop",
#         "quilt shop",
#         "food store",
#         "campground",
#         "farmstay",
#         "modern indian restaurant",
#         "carpet store",
#         "paintings store",
#         "aquarium shop",
#         "general store",
#         "vegan restaurant",
#         "coffee store",
#         "meyhane",
#         "swimwear store",
#         "south indian restaurant",
#         "live music bar",
#         "hospital",
#         "home audio store",
#         "drug store",
#         "kitchen furniture store",
#         "trading company",
#         "cantonese restaurant",
#         "pakistani restaurant",
#         "air conditioning store",
#         "coffee wholesaler",
#         "espresso bar",
#         "seafood restaurant",
#         "asian restaurant",
#         "shabu-shabu restaurant",
#         "halal restaurant",
#         "sundae restaurant",
#         "used clothing store",
#         "brewpub",
#         "childrens amusement center",
#         "football club",
#         "hospitality and tourism school",
#         "cafeteria",
#         "leather goods store",
#         "natural goods store",
#         "aged care",
#         "hardware store",
#         "fujian restaurant",
#         "catering food and drink supplier",
#         "frozen yogurt shop",
#         "tiffin center",
#         "shopping mall",
#         "coffee stand",
#         "grill",
#         "chinaware store",
#         "dairy store",
#         "athletic park",
#         "antique store",
#         "wholesale grocer",
#         "shop supermarket furniture store",
#         "game store",
#         "smoke shop",
#         "hypermarket",
#         "fishing store",
#         "candy store",
#         "cosmetics store",
#         "piedmontese restaurant",
#         "pet supply store",
#         "punjabi restaurant",
#         "bridal shop",
#         "bar & grill",
#         "pizza takeaway",
#         "korean restaurant",
#         "authentic japanese restaurant",
#         "psychiatric hospital",
#         "lunch restaurant",
#         "industrial supermarket",
#         "books wholesaler",
#         "warehouse store",
#         "lumber store",
#         "general hospital",
#         "auto auction",
#         "fish store",
#         "baby clothing store",
#         "organic shop",
#         "convenience store",
#         "animal feed store",
#         "greek restaurant",
#         "refrigerator store",
#         "bagel shop",
#         "art studio",
#         "dessert restaurant",
#         "udon noodle restaurant",
#         "hawker center",
#         "barber shop",
#         "dessert shop",
#         "vintage clothing store",
#         "doner kebab restaurant",
#         "computer software store",
#         "government hospital",
#         "pizza restaurant",
#         "supermarket",
#         "barbecue restaurant",
#         "hotel",
#         "coffee shop",
#         "restaurant",
#         "fast food restaurant",
#         "cafe",
#         "lounge",
#         "bar",
#         "beer store",
#         "dollar store",
#         "gas station",
#         "clothing store",
#         "shopping mall",
#     ],
#     "group 3": [
#         "bilingual school",
#         "art school",
#         "police academy",
#         "painting lessons",
#         "chinese language school",
#         "police",
#         "painting",
#         "school",
#         "library",
#         "art gallery",
#         "alliance church",
#         "international school",
#         "montessori school",
#         "hospitality and tourism school",
#         "combined primary and secondary school",
#         "public educational institution",
#         "heritage museum",
#         "embassy",
#         "police academy",
#         "drivers license training school",
#         "community center",
#         "foreign consulate",
#         "community school",
#         "foreign languages program school",
#         "law school",
#         "english language school",
#         "ballet school",
#         "primary school",
#         "learning center",
#         "heritage preservation",
#         "catholic school",
#         "public library",
#     ],
#     "group 4": [
#         "atm",
#         "currency exchange service",
#         "investment bank",
#         "savings bank",
#         "bank or atm",
#         "cooperative bank",
#         "credit union",
#         "loan agency",
#         "private sector bank",
#     ],
# }


GROUPS = {
    "group1": [
        "service",
        "boat tour agency",
        "company",
        "airline",
        "stadium",
        "airport",
        "international airport",
        "regional airport",
        "domestic airport",
        "military airport",
        "airstrip",
        "bus station",
        "bus stop",
        "bus depot",
        "train station",
        "subway station",
        "transit station",
        "transport hub",
        "cable car station",
        "ferry terminal",
        "gondola lift station",
        "heliport",
        "seaplane base",
        "rest stop",
        "weigh station",
        "taxi stand",
        "bridge",
        "park & ridetourist attraction",
        "amusement park",
        "theme park",
        "museum",
        "art museum",
        "archaeological museum",
        "ethnographic museum",
        "handicraft museum",
        "heritage museum",
        "history museum",
        "local history museum",
        "modern art museum",
        "natural history museum",
        "open air museum",
        "toy museum",
        "war museum",
        "army museum",
        "museum of zoology",
        "historical landmark",
        "memorial estate",
        "scenic spot",
        "national park",
        "ecological park",
        "city park",
        "pilgrimage place",
        "historical place museum",
        "observation deck",
        "roller coaster",
        "hiking area",
        "school",
        "university",
        "public university",
        "private university",
        "college",
        "technical university",
        "business school",
        "medical school",
        "law school",
        "technical school",
        "higher secondary school",
        "high school",
        "secondary school",
        "primary school",
        "elementary school",
        "middle school",
        "combined primary and secondary school",
        "k-12 school",
        "special education school",
        "school for the deaf",
        "senior high school",
        "agricultural high school",
        "religious school",
        "community school",
        "general education school",
        "catholic school",
        "montessori school",
        "international school",
        "bilingual school",
        "language school",
        "english language school",
        "chinese language school",
        "educational institution",
        "public educational institution",
        "private educational institution",
        "learning center",
        "education center",
        "research institute",
        "institute of technology",
        "polytechnic institute",
        "open university",
        "academic departmentcity hall",
        "local government office",
        "government office",
        "county government office",
        "courthouse",
        "city courthouse",
        "district court",
        "county court",
        "magistrates court",
        "district justice",
        "embassy",
        "foreign consulate",
        "legal affairs bureau",
        "customs office",
        "drivers license office",
        "visa and passport office",
        "public safety office",
        "sheriffs department",
        "government",
        "village hallhospital",
        "hospital",
        "general hospital",
        "university hospital",
        "specialized hospital",
        "government hospital",
        "military hospital",
        "veterans hospital",
        "heart hospital",
        "maternity hospital",
        "private hospital",
        "psychiatric hospital",
        "medical center",
        "medical clinic",
        "rehabilitation center",
        "cancer treatment centerparking",
        "public parking space",
        "parking lot",
        "park",
        "parking garage",
        "free parking lot",
        "tsukigime parking lot",
        "parking lot for bicycles",
        "parking lot for motorcycles",
        "valet parking service",
        "stadium",
        "sports complex",
        "athletic field",
        "athletic park",
        "american football field",
        "soccer field",
        "tennis court",
        "swimming pool",
        "public swimming pool",
        "indoor swimming pool",
        "volleyball court",
        "badminton court",
        "athletic track",
        "pickleball court",
        "rowing area",
        "post office",
    ],
    "group2": [
        "campground",
        "movie theater",
        "brewpub",
        "retail stores",
        "store",
        "hotel",
        "pho restaurant",
        "lodge",
        "restaurant",
        "shopping mall",
        "department store",
        "supermarket",
        "discount supermarket",
        "hypermarket",
        "warehouse store",
        "variety store",
        "outlet store",
        "outlet mall",
        "industrial supermarket",
        "market",
        "fresh food market",
        "convenience store",
        "dollar store",
        "general store",
        "clothing store",
        "womens clothing store",
        "mens clothing store",
        "childrens clothing store",
        "youth clothing store",
        "plus size clothing store",
        "formal wear store",
        "sportswear store",
        "beach clothing store",
        "work clothes store",
        "baby clothing store",
        "lingerie store",
        "underwear store",
        "shoe store",
        "boot store",
        "orthopedic shoe store",
        "jewelry store",
        "watch store",
        "sunglasses store",
        "hat shop",
        "dress store",
        "bridal shop",
        "t-shirt store",
        "uniform store",
        "traditional kostume store",
        "bakery",
        "wedding bakery",
        "butcher shop",
        "shop",
        "poultry store",
        "fish store",
        "seafood store",
        "greengrocer",
        "fruit and vegetable store",
        "grocery store",
        "american grocery store",
        "asian grocery store",
        "chinese supermarket",
        "european grocery store",
        "filipino grocery store",
        "indian grocery store",
        "italian grocery store",
        "japanese grocery store",
        "korean grocery store",
        "russian grocery store",
        "gourmet grocery store",
        "food store",
        "organic food store",
        "organic shop",
        "health food store",
        "liquor store",
        "beer store",
        "wine store",
        "state liquor store",
        "coffee store",
        "tea store",
        "spice store",
        "herb shop",
        "rice shop",
        "fruit parlor",
        "tofu shop",
        "dessert shop",
        "ice cream shop",
        "frozen yogurt shop",
        "gift shop",
        "souvenir store",
        "gift basket store",
        "hallmark store",
        "florist",
        "dried flower shop",
        "plant nursery",
        "garden center",
        "tree farm",
        "toy store",
        "childrens store",
        "comic book store",
        "game store",
        "video game store",
        "book store",
        "childrens book store",
        "used book store",
        "rare book store",
        "religious book store",
        "computer store",
        "computer accessories store",
        "used computer store",
        "electronics store",
        "home audio store",
        "cell phone store",
        "mobile phone repair shop",
        "pet store",
        "bird shop",
        "goldfish store",
        "aquarium shop",
        "motorcycle shop",
        "motorcycle parts store",
        "car accessories store",
        "used auto parts store",
        "tire shop",
        "wheel store",
        "racing car parts parts store",
        "auto parts store",
        "electric bicycle store",
        "bicycle store",
        "sporting goods store",
        "outdoor sports store",
        "running store",
        "golf shop",
        "soccer store",
        "fishing store",
        "sports card store",
        "trophy shop",
        "hunting and fishing store",
        "motorsports store",
        "kitchen supply store",
        "appliance store",
        "refrigerator store",
        "washer & dryer store",
        "hardware store",
        "tool store",
        "paint store",
        "home improvement store",
        "furniture store",
        "office furniture store",
        "kitchen furniture store",
        "bedroom furniture store",
        "childrens furniture store",
        "rustic furniture store",
        "unfinished furniture store",
        "pine furniture shop",
        "amish furniture store",
        "cane furniture store",
        "bar restaurant furniture store",
        "outdoor furniture store",
        "garden furniture shop",
        "home goods store",
        "bedding store",
        "bed shop",
        "mattress store",
        "waterbed store",
        "bathroom supply store",
        "beauty supply store",
        "cosmetics store",
        "health and beauty shop",
        "pharmaceutical products wholesaler",
        "drug store",
        "pharmacy",
        "homeopathic pharmacy",
        "veterinary pharmacy",
        "parapharmacy",
        "optical shop",
        "photo shop",
        "camera store",
        "sign shop",
        "neon sign shop",
        "art supply store",
        "craft store",
        "scrapbooking store",
        "sewing shop",
        "knitting shop",
        "yarn store",
        "costume store",
        "photocopiers supplier",
        "printing supply store",
        "copying supply store",
        "paper store",
        "screen store",
        "blinds shop",
        "curtain store",
        "window treatment store",
        "tile store",
        "carpet store",
        "countertop store",
        "cabinet store",
        "bathroom remodeler",
        "cookware store",
        "knife store",
        "cutlery store",
        "glass shop",
        "glass & mirror shop",
        "marine supply store",
        "agricultural service",
        "camping store",
        "rv park",
        "smoke shop",
        "cigar shop",
        "tobacco shop",
        "antique store",
        "antique furniture store",
        "architectural salvage store",
        "second hand store",
        "thrift store",
        "consignment shop",
        "used clothing store",
        "vintage clothing store",
        "junk store",
        "pawn shop",
        "candle store",
        "stationery store",
        "party supply store",
        "balloon store",
        "cd store",
        "record store",
        "musical instrument store",
        "guitar store",
        "drum store",
        "piano store",
        "electronic parts supplier",
        "boutique",
        "showroom",
        "shop supermarket furniture store",
        "beauty products wholesaler",
        "cosmetics wholesaler",
        "appliance parts supplier",
        "cosmetic products manufacturer",
        "stained glass studio",
        "seasonal goods store",
        "reproduction furniture store",
        "wicker store",
        "food courtrestaurant",
        "cafe",
        "fast food restaurant",
        "fine dining restaurant",
        "breakfast restaurant",
        "brunch restaurant",
        "lunch restaurant",
        "family restaurant",
        "barbecue restaurant",
        "steak house",
        "seafood restaurant",
        "pizza restaurant",
        "sushi restaurant",
        "italian restaurant",
        "french restaurant",
        "chinese restaurant",
        "mexican restaurant",
        "thai restaurant",
        "indian restaurant",
        "japanese restaurant",
        "korean restaurant",
        "mediterranean restaurant",
        "vietnamese restaurant",
        "turkish restaurant",
        "greek restaurant",
        "german restaurant",
        "american restaurant",
        "european restaurant",
        "asian restaurant",
        "african restaurant",
        "caribbean restaurant",
        "arab restaurant",
        "egyptian restaurant",
        "vegetarian restaurant",
        "vegan restaurant",
        "gluten-free restaurant",
        "organic restaurant",
        "health food restaurant",
        "raw food restaurant",
        "buffet restaurant",
        "noodle shop",
        "hot pot restaurant",
        "ramen restaurant",
        "udon noodle restaurant",
        "dan dan noodle restaurant",
        "diner",
        "fish restaurant",
        "chicken restaurant",
        "fried chicken takeaway",
        "chicken wings restaurant",
        "chicken shop",
        "soup shop",
        "salad shop",
        "sandwich shop",
        "hot dog stand",
        "bagel shop",
        "pastry shop",
        "cake shop",
        "confectionery store",
        "chocolate cafe",
        "deli",
        "hawker center",
        "hawker stall",
        "food truck",
        "juice shop",
        "coffee shop",
        "espresso bar",
        "coffee stand",
        "coffee roasters",
        "tea house",
        "traditional teahouse",
        "pizza takeaway",
        "indian takeaway",
        "takeout restaurant",
        "bar",
        "pub",
        "sports bar",
        "wine bar",
        "beer garden",
        "beer hall",
        "night club",
        "dance club",
        "dance hall",
        "karaoke",
        "karaoke bar",
        "lounge",
        "cocktail bar",
        "hookah bar",
        "blues club",
        "club",
        "stand bar",
        "frituur",
        "churreria",
        "chop bar",
        "tiffin center",
        "snack bar",
        "meyhane",
        "live music bar",
        "gastropub",
        "brasserie",
        "bistro",
        "drive-in movie theater",
        "amusement park",
        "childrens amusement center",
        "tourist attraction",
        "swimming facility",
        "swim club",
        "athletic club",
        "gym",
        "boxing gym",
        "muay thai boxing gym",
        "fitness center",
        "physical fitness program",
        "health spa",
        "spa",
        "spa and health club",
        "recreation center",
        "sauna",
        "massage spa",
        "indoor playground",
        "indoor cycling",
        "shopping mallhotel",
        "motel",
        "love hotel",
        "capsule hotel",
        "extended stay hotel",
        "resort hotel",
        "lodging",
        "indoor lodging",
        "homestay",
        "farmstay",
        "serviced accommodation",
        "holiday apartment",
        "holiday apartment rental",
        "holiday home",
        "bed & breakfast",
        "guest house",
        "youth hostel",
        "hostel",
        "cottage",
        "mountain cabin",
        "cottage rental",
        "country house",
        "dude ranch",
        "camping cabin",
        "villa",
        "boarding house",
        "serviced apartment",
        "executive suite rental agency",
        "condominium rental agency",
        "apartment rental agency",
        "short term apartment rental agency",
        "apartment building",
        "apartment complex",
        "condominium complex",
        "townhouse complex",
        "housing complex",
        "housing development",
        "housing society",
        "furnished apartment building",
        "car dealer",
        "used car dealer",
        "hyundai dealer",
        "toyota dealer",
        "car wash",
        "car rental agency",
        "limousine service",
        "chauffeur service",
        "gas station",
        "gas shop",
        "alternative fuel station",
        "electric vehicle charging station",
    ],
    "group3": [
        "educational institutions",
        "school",
        "library",
        "public library",
        "university library",
        "law library",
        "childrens library",
        "toy library",
        "film and photograph library",
        "national library",
        "martial arts school",
        "taekwondo school",
        "self defense school",
        "jujitsu school",
        "kickboxing school",
        "art school",
        "farm school",
        "nursery school",
        "kindergarten",
        "preschool",
        "playgroup",
        "religious school",
        "military school",
        "police academy",
        "cramming school",
        "hospitality and tourism school",
        "vocational school",
        "adult education school",
        "computer training school",
        "driving school",
        "english language camp",
        "motorcycle driving school",
        "drivers license training school",
        "ballet school",
        "summer camp organizer",
        "childrens camp",
        "coaching center",
        "cue sports school",
        "head start center",
        "swimming school",
        "baby swimming school",
        "life coach",
        "personal trainer",
        "womens personal trainer",
        "aerobics instructor",
        "ballroom dance instructor",
        "vocal instructor",
        "guitar instructor",
        "piano instructor",
        "swimming instructor",
        "physical therapist",
        "yoga instructor",
        "yoga studio",
        "pilates studio",
        "study at home school",
        "makerspace",
        "childrens club",
        "childrens party service",
        "childrens farm",
        "drawing lessons",
        "painting lessons",
        "cooking class",
        "body shaping class",
        "aero dance class",
        "hip hop dance class",
        "educational supply store",
        "school supply store",
        "child health care centre",
        "school center",
        "school administration office",
        "school bus service",
        "preparatory school",
        "grammar school",
        "childminder",
        "girls high school",
        "art gallery",
        "art studio",
        "art cafe",
        "art center",
        "art dealer",
        "artist",
        "handicraft",
        "artistic handicrafts",
        "painting",
        "painter",
        "painting studio",
        "sculpture",
        "musical club",
        "arts organization",
        "chamber of handicrafts",
        "performing arts group",
        "handicraft school",
        "community center",
        "children hall",
        "flamenco dance store",
        "chess club",
        "pool billard club",
        "sports club",
        "soccer club",
        "football club",
        "fishing club",
        "gymnastics club",
        "boxing club",
        "sports school",
        "martial arts club",
        "gymnastics center",
        "event venue",
        "wedding venue",
        "banquet hallplace of worship",
        "religious institution",
        "congregation",
        "spiritist center",
        "alliance churchpolice",
        "civil police",
        "state police",
        "federal police",
        "police station",
        "traffic police station",
        "police department",
        "department of public safety",
        "fire station",
        "police",
    ],
    "group4": [
        "bank",
        "atm",
        "bank or atm",
        "private sector bank",
        "cooperative bank",
        "credit union",
        "savings bank",
        "investment bank",
        "financial institution",
        "financial consultant",
        "investment service",
        "investment company",
        "property investment company",
        "currency exchange service",
        "loan agency",
    ],
}
