# these categories also google places api types from https://developers.google.com/maps/documentation/places/web-service/supported_types

POI_GROUPS = {
    "group1": {
        "amusement_park",
        "airport",
        "bus_station",
        "train_station",
        "transit_station",
        "store",
        "post_office",
        "tourist_attraction",
        "school",
        "university",
        "city_hall",
        "local_government_office",
        "courthouse",
        "embassy",
        "museum",
        "stadium",
        "gym",
        "parking",
        "hospital",
    },
    "group2": {
        "car_dealer",
        "hospital",
        "restaurant",
        "cafe",
        "amusement_park",
        "tourist_attraction",
        "clothing_store",
        "movie_theater",
        "shopping_mall",
        "supermarket",
        "shopping_mall",
        "pharmacy",
        "book_store",
        "store",
        "home_goods_store",
        "convenience_store",
        "gas_station",
        "lodging",
        "convenience_store",
    },
    "group3": {
        "school",
        "library",
        "art_gallery",
        "police",
        "place_of_worship",
    },
    "group4": {"bank", "atm"},
}


ALL_TYPES = set().union(*POI_GROUPS.values())

AREAS = [
    "an_giang",
    "bac_giang",
    "bac_lieu",
    "binh_dinh",
    "binh_duong",
    "binh_phuoc",
    "binh_thuan",
    "ca_mau",
    "can_tho",
    "cao_bang",
    "dak_nong",
    "da_nang",
    "dong_nai",
    "gia_lai",
    "ha_giang",
    "ha_nam",
    "hau_giang",
    "hcm",
    "hoa_binh",
    "hung_yen",
    "khanh_hoa",
    "kien_giang",
    "kon_tum",
    "lai_chau",
    "lam_dong",
    "lang_son",
    "long_an",
    "nghe_an",
    "ninh_binh",
    "ninh_thuan",
    "phu_yen",
    "quang_nam",
    "quang_ngai",
    "quang_ninh",
    "quang_tri",
    "soc_trang",
    "tay_ninh",
    "thai_nguyen",
    "thanh_hoa",
    "tien_giang",
    "tra_vinh",
    "tuyen_quang",
    "vinh_long",
    "vung_tau",
    "yen_bai",
    "hue",
    "bac_kan",
    "bac_ninh",
    "ben_tre",
    "dak_lak",
    "dien_bien",
    "dong_thap",
    "hai_duong",
    "hai_phong",
    "ha_noi",
    "ha_tinh",
    "lao_cai",
    "nam_dinh",
    "phu_tho",
    "quang_binh",
    "quang_ngai",
    "son_la",
    "thai_binh",
    "vinh_phuc",
]
